{ lib, ... }:
let
  proxyPort = 2080;

  # Домены, которые всегда DIRECT/Не через прокси
  directDomains = [
    "localhost"
    "127.0.0.1"
    "apple.com"
    "icloud.com"
    "mzstatic.com"
    "local"

    # Steam
    "steampowered.com"
    "steamcommunity.com"
    "steamstatic.com"
    "steamcontent.com"
    "akamaihd.net"
    "cloudflare.steamstatic.com"
  ];

  mkHostMatch = domains:
    lib.concatStringsSep " ||\n      "
      (map (d: ''dnsDomainIs(host, "${d}") || shExpMatch(host, "*.${d}")'') domains);
in
{
  home.file.".config/proxy/auto.pac".text = ''
    // Generated by home-manager (proxy-pac.nix)
    function FindProxyForURL(url, host) {
      // normalize host (strip :port)
      host = host.split(":")[0];

      // 0) plain hostnames go direct (e.g., intranet, printer)
      if (isPlainHostName(host)) {
        return "DIRECT";
      }

      // 1) explicit DIRECT domains
      if (
        ${mkHostMatch directDomains}
      ) {
        return "DIRECT";
      }

      // 2) Local/private networks go DIRECT (resolve domains -> IP first)
      //    This makes internal/corp domains work correctly if they resolve into RFC1918 space.
      var ip = dnsResolve(host);
      if (ip) {
        if (
          isInNet(ip, "127.0.0.0", "255.0.0.0") ||
          isInNet(ip, "10.0.0.0",  "255.0.0.0") ||
          isInNet(ip, "172.16.0.0","255.240.0.0") ||
          isInNet(ip, "192.168.0.0","255.255.0.0") ||
          isInNet(ip, "169.254.0.0","255.255.0.0") // link-local
        ) {
          return "DIRECT";
        }
      }

      // 3) Default: everything else via proxy (with fallback to DIRECT if proxy is down)
      return "SOCKS5 127.0.0.1:${toString proxyPort}; DIRECT";
    }
  '';
}